# Generated by Django 4.2.30 on 2026-06-09 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_email_delivery_status_booking_email_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupbooking',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_bookings', to='bookings.booking'),
        ),
    ]
