# Generated by Django 4.2.30 on 2026-06-09 09:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_groupbooking_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='category',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Silver', max_length=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=8),
        ),
    ]
