# Generated by Django 4.2.30 on 2026-06-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_booking_is_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinePointsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_booking', models.IntegerField(default=10)),
                ('first_booking_bonus', models.IntegerField(default=50)),
                ('campaign_active', models.BooleanField(default=False)),
                ('campaign_bonus_points', models.IntegerField(default=20)),
                ('campaign_name', models.CharField(default='Summer Festival Bonus', max_length=255)),
                ('redemption_rules', models.JSONField(default=dict)),
            ],
        ),
    ]
