# Generated by Django 4.2.30 on 2026-06-08 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=500)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='authentication.location')),
            ],
        ),
        migrations.CreateModel(
            name='SportsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('banner', models.URLField(max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('stadium_name', models.CharField(max_length=255)),
                ('stadium_details', models.TextField(blank=True, null=True)),
                ('match_timings', models.CharField(help_text='e.g. 4:00 PM - 8:00 PM', max_length=100)),
                ('seating_information', models.TextField(blank=True, help_text='Details about seating sections', null=True)),
                ('available_seats', models.IntegerField(default=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_events', to='events.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Workshops', 'Workshops'), ('Comedy Shows', 'Comedy Shows'), ('Music Shows', 'Music Shows'), ('Performages', 'Performances'), ('Kids Events', 'Kids Events'), ('Spirituality', 'Spirituality'), ('Award Shows', 'Award Shows'), ('Role Play Events', 'Role Play Events')], max_length=100)),
                ('banner', models.URLField(max_length=1000)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('available_seats', models.IntegerField(default=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.venue')),
            ],
        ),
    ]
