# Generated by Django 4.2.30 on 2026-06-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='Customer', max_length=20),
        ),
    ]
