# Generated by Django 4.2.30 on 2026-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_theatre_address_theatre_contact_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatre',
            name='is_demo',
            field=models.BooleanField(default=False, help_text='Mark theatre as demo for testing'),
        ),
    ]
