# Generated by Django 4.2.30 on 2026-06-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_theatre_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='seat_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
